#!/usr/bin/env bash

dir=$(dirname "$0")

run_node() {
  # TODO: take WOOL_PATH from env
  # TODO: get the loader path relative to WOOL_PATH from env
  WOOL_PATH=$PWD/__mock-home/.wool/ \
  WOOL_ENTRY=$1 \
  node --experimental-modules --loader $PWD/workspaces/loader/src/loader.mjs $*
}

if [[ $1 == *.mjs ]]
then
  run_node $1
else
  run_node "${dir}/src/cli.mjs" $*
fi
